### ISSUE TITLE
New model names break tests

### ISSUE THREAD

**Issue by brettc** [brettc/partitionfinder#46]
The new model loading doesn't have names for a number of options contained in the tests (ie. 'raxml'). This breaks a number of tests.

**Comment by roblanf** [comment]
I'll work on re-implementing the model names. The tests might still fail,
because some options (like 'raxml') might now give different answers. But
one thing at a time I guess.

On 27 June 2015 at 03:39, Brett Calcott <notifications@github.com> wrote:

> The new model loading doesn't have names for a number of options contained
> in the tests (ie. 'raxml'). This breaks a number of tests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/46>.
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by roblanf** [comment]
Done. And also updated in the manual.
