### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#98]
@brettc, can you take a look at these. 

I have a small number of tests failing, all because of very small differences in the expected and observed AIC/BIC scores. There's a full list below. I think we need to do two things here:

1. Update the expected values to the new observed values (the diffs appear to be caused by changes in likeilhoods from Phyml/RAxML).

2. Increase the tolerance limit to, say, 1.0. Right now it's 0.1, and this often means we get these false positives with failing tests. 1.0 is small, but big enough to be robust to very small changes in the calculations from phyml/raxml.

R

**Comment by roblanf** [comment]
Here are the failing tests. Every fail is down to small diffs in AIC/BIC:

```

tests/full_analysis/test_full.py::test_dna[DNA1] PASSED
tests/full_analysis/test_full.py::test_dna[DNA2] FAILED
tests/full_analysis/test_full.py::test_dna[DNA3] FAILED
tests/full_analysis/test_full.py::test_dna[DNA4] FAILED
tests/full_analysis/test_full.py::test_dna[DNA5] FAILED
tests/full_analysis/test_full.py::test_dna[DNA6] PASSED
tests/full_analysis/test_full.py::test_dna[DNA7] FAILED
tests/full_analysis/test_full.py::test_dna[DNA8] PASSED
```

**Comment by brettc** [comment]
Ok -- will check this out (currently writing grants, so won't be straight away).

**Comment by roblanf** [comment]
Yo @brettc, this is me, bugging you. But you're not allowed to use the server right now (running analyses for the ms...).

**Comment by brettc** [comment]
I believe this is now fixed in the main branch. Can you test?

**Comment by brettc** [comment]
The latest version of raxml appears to fix the outstanding testing problems. Do we have a consensus on what raxml version we compile and distribute (I used the avx.mac version)

**Comment by roblanf** [comment]
I use the SSE3 makefiles. Remember we need pthreads and not pthreads
compiled separately.

About to check the tests. Awesome that the new RAxML seems to fix the
broken one.

On 24 June 2016 at 21:50, Brett Calcott <notifications@github.com> wrote:

> The latest version of raxml appears to fix the outstanding testing
> problems. Do we have a consensus on what raxml version we compile and
> distribute (I used the avx.mac version)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/98#issuecomment-228326119>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA2pE8Jq9FRrKM03Chdihm6gyAL32d1Wks5qO8RqgaJpZM4Idmr8>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by brettc** [comment]
I vaguely remember discussing this. Did we document it anywhere?

**Comment by roblanf** [comment]
didn't you have a build script somewhere? If not, we could/should do that.
However, my take is really that we can provide best guesses, and folks can
compile their own versions if ours don't work.

On 25 June 2016 at 12:02, Brett Calcott <notifications@github.com> wrote:

> I vaguely remember discussing this. Did we document it anywhere?
>
> On Sat, Jun 25, 2016 at 1:16 PM roblanf <notifications@github.com> wrote:
>
> > I use the SSE3 makefiles. Remember we need pthreads and not pthreads
> > compiled separately.
> >
> > About to check the tests. Awesome that the new RAxML seems to fix the
> > broken one.
> >
> > On 24 June 2016 at 21:50, Brett Calcott <notifications@github.com>
> wrote:
> >
> > > The latest version of raxml appears to fix the outstanding testing
> > > problems. Do we have a consensus on what raxml version we compile and
> > > distribute (I used the avx.mac version)
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/brettc/partitionfinder/issues/98#issuecomment-228326119
> > >,
> > > or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AA2pE8Jq9FRrKM03Chdihm6gyAL32d1Wks5qO8RqgaJpZM4Idmr8
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Rob Lanfear
> > School of Biological Sciences,
> > Macquarie University,
> > Sydney
> >
> > phone: +61 (0)2 9850 8204
> >
> > www.robertlanfear.com
> >
> > —
> > You are receiving this because you were mentioned.
> >
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/brettc/partitionfinder/issues/98#issuecomment-228498888
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAb6Q9JGltd0_qUOQGb-ahMtANE1wqFBks5qPIF8gaJpZM4Idmr8
> >
> > .
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/98#issuecomment-228501193>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA2pE4-Lg6LQKYDguU2t9eptz1w-Tb1sks5qPIwbgaJpZM4Idmr8>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by brettc** [comment]
There is a build script, but it only builds one binary. Let's chat about
this and nail down some defaults.

**Comment by cmayer** [comment]
Hi all,

we needed the two binaries, since the pthreads is used for the ml starting tree.
The single threaded version was necessary for the main run.
The pthreads version uses a minimum of 2 threads and for several reasons we
preferred the single threaded version.
- There used to be problems in the pthread version which did not occur in the single
threaded version.
- If PF can start N raxml runs with one thread this is more efficient than starting N/M runs with M threads.

Best
Christoph


Am 25.06.2016 um 11:26 schrieb Brett Calcott <notifications@github.com>:

> There is a build script, but it only builds one binary. Let's chat about
> this and nail down some defaults.
> 
> On Sat, Jun 25, 2016 at 2:31 PM roblanf <notifications@github.com> wrote:
> 
> > didn't you have a build script somewhere? If not, we could/should do that.
> > However, my take is really that we can provide best guesses, and folks can
> > compile their own versions if ours don't work.
> >
> > On 25 June 2016 at 12:02, Brett Calcott <notifications@github.com> wrote:
> >
> > > I vaguely remember discussing this. Did we document it anywhere?
> > >
> > > On Sat, Jun 25, 2016 at 1:16 PM roblanf <notifications@github.com>
> > wrote:
> > >
> > > > I use the SSE3 makefiles. Remember we need pthreads and not pthreads
> > > > compiled separately.
> > > >
> > > > About to check the tests. Awesome that the new RAxML seems to fix the
> > > > broken one.
> > > >
> > > > On 24 June 2016 at 21:50, Brett Calcott <notifications@github.com>
> > > wrote:
> > > >
> > > > > The latest version of raxml appears to fix the outstanding testing
> > > > > problems. Do we have a consensus on what raxml version we compile and
> > > > > distribute (I used the avx.mac version)
> > > > >
> > > > > —
> > > > > You are receiving this because you authored the thread.
> > > > > Reply to this email directly, view it on GitHub
> > > > > <
> > > >
> > >
> > https://github.com/brettc/partitionfinder/issues/98#issuecomment-228326119
> > > > >,
> > > > > or mute the thread
> > > > > <
> > > >
> > >
> > https://github.com/notifications/unsubscribe/AA2pE8Jq9FRrKM03Chdihm6gyAL32d1Wks5qO8RqgaJpZM4Idmr8
> > > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Rob Lanfear
> > > > School of Biological Sciences,
> > > > Macquarie University,
> > > > Sydney
> > > >
> > > > phone: +61 (0)2 9850 8204
> > > >
> > > > www.robertlanfear.com
> > > >
> > > > —
> > > > You are receiving this because you were mentioned.
> > > >
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > >
> > https://github.com/brettc/partitionfinder/issues/98#issuecomment-228498888
> > > >,
> > > > or mute the thread
> > > > <
> > >
> > https://github.com/notifications/unsubscribe/AAb6Q9JGltd0_qUOQGb-ahMtANE1wqFBks5qPIF8gaJpZM4Idmr8
> > > >
> > > > .
> > >
> > > >
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <
> > https://github.com/brettc/partitionfinder/issues/98#issuecomment-228501193
> > >,
> > > or mute the thread
> > > <
> > https://github.com/notifications/unsubscribe/AA2pE4-Lg6LQKYDguU2t9eptz1w-Tb1sks5qPIwbgaJpZM4Idmr8
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Rob Lanfear
> > School of Biological Sciences,
> > Macquarie University,
> > Sydney
> >
> > phone: +61 (0)2 9850 8204
> >
> > www.robertlanfear.com
> >
> > —
> >
> >
> > You are receiving this because you were mentioned.
> >
> > Reply to this email directly, view it on GitHub
> > <https://github.com/brettc/partitionfinder/issues/98#issuecomment-228502900>,
> > or mute the thread
> > <https://github.com/notifications/unsubscribe/AAb6Q_rwEgzKiMQuu8KnlPueL5cJ8aTUks5qPJMNgaJpZM4Idmr8>
> > .
> >
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

****************************************
Dr. Christoph Mayer
Email:  c.mayer.zfmk@uni-bonn.de
Tel.:   +49 (0)228 9122 403

Zoologisches Forschungsmuseum Alexander Koenig
- Leibniz Institut für Biodiversität der Tiere -
Adenauerallee 160
53113 Bonn, Germany 
www.zfmk.de

Stiftung des öffentlichen Rechts; Direktor: Prof. J. W. Wägele
Sitz: Bonn
****************************************

**Comment by roblanf** [comment]
I am still getting the same few tests failing. All because of v. minor diffs in AIC/BIC scores. 

I decided to increase the MAX_ERROR to 1.0, since all the diffs I get are really very small, and these tests keep taking our time unnecessarily. I'll see how it goes.

Basically, we want to know that the results are close enough. The old threshold (0.1) is small enough that differences in machine, OS, and random number seed can be enough to make the test fail. That is not the intention. The intention is to catch big changes.

**Comment by cmayer** [comment]
Dear Rob and Brett,

while running PF analyses again I stumbled over the following issue:

I am using 24 cores and I had a look in the phylofiles folder to see what the PF is working on.
Looking at the file names, one can see the model raxml is using at the moment.
My observation was: While analysing the starting scheme, - most of the time I looked in the phylofiles folder I only saw LG4X models running.
In very rare cases one or two threads worked on other models, but soon all where working on LG4X models again.
When thinking about this for a short time I came to the conclusion that this implies that the LG4X model must
take more time than all other models together. I would even say: time for all models * N < time for LG4X
where N >= probably 24, since otherwise I would expect to see more threads working on other models.  

I remembered that I had thought about this before and that there will be a problem towards the end of the analysis, if the number of subsets 
PF is working on gets small. PF will often only use one thread even though it could use a large number of threads.

Well, a quick look at the code showed me that you must have had some similar ideas before:
You sort subsets by length and you introduce a difficulty for the models. Then you analyse long
subsets before shorter ones and more difficult models before less difficult models.
So maybe everything is already OK I thought. Irrespective of the order, if the LG4X model is much slower
all threads can just be stuck when analysing the LG4X model.
But then I found that the LG4X is always analysed as the last model, which is non optimal, if it takes more time.
Looking even further I found that I can obtain the final model difficulty by increasing the verbosity.

Doing this I obtain as part of the debug information:
DEBUG    | 2016-06-26 03:05:05,417 | raxml_mode |       Model: DCMUT+G Difficulty: 2002
DEBUG    | 2016-06-26 03:05:05,425 | raxml_mode |       Model: WAG+G+F Difficulty: 5022
DEBUG    | 2016-06-26 03:05:05,430 | raxml_mode |       Model: LG+G Difficulty: 2002
DEBUG    | 2016-06-26 03:05:05,436 | raxml_mode |       Model: JTT+G+F Difficulty: 5022
DEBUG    | 2016-06-26 03:05:05,441 | raxml_mode |       Model: LG4X Difficulty: 6

So it appears to me that the model difficulty is very low for LG4X even though it takes more time than all other models together.
This could be made more efficient if the model difficulty of the LG4X model would be increased above that of the +G+F models.

I have another idea, which unfortunately is probably much more difficult to implement:

While the PF is waiting for the last slow model to complete, it could use its threads to work on subsets that are not needed for this step,
but which have a good chance that they are needed in future steps. Even for higher step numbers, PF often needs to analyse pairs or triples
of data blocks. So even if rcluster-max is set to say 1000, the PF could use the "idle time" to analyse the next most promising candidates beyond the 1000 limit.
Their result is kept "on hold" and not used until this combination of data blocks has to be computed. This procedure might 
analyse some combinations that are never needed, but I would guess that a lot of combinations are indeed needed in future steps.
I agree that implementing this is far from trivial. 

Best
Christoph


****************************************
Dr. Christoph Mayer
Email:  c.mayer.zfmk@uni-bonn.de
Tel.:   +49 (0)228 9122 403

Zoologisches Forschungsmuseum Alexander Koenig
- Leibniz Institut für Biodiversität der Tiere -
Adenauerallee 160
53113 Bonn, Germany 
www.zfmk.de

Stiftung des öffentlichen Rechts; Direktor: Prof. J. W. Wägele
Sitz: Bonn
****************************************

**Comment by roblanf** [comment]
Fixed. In the end I changed the error threshold to 10 units. This is not a big deal. On the scale of measurement, 10 units is still very sensitive to changes in the underlying partitioning scheme and/or models. This should decrease our false positive rate a lot, without (I hope!) giving us too many false negatives.

**Comment by roblanf** [comment]
ALL TESTS PASSING: https://github.com/brettc/partitionfinder/commit/7d4c115dd5327bb6b2c3299a153d10596eba9ef3
